services:
  postgres:
    image: postgres:14.23-alpine3.24
    container_name: meshAIPostgres
    restart: always
    ports:
      - "${PORT_DB_HOST:-5432}:${PG_CONTAINER_PORT:-5432}"
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB_NAME}
    networks:
      - meshAINetwork
    volumes:
      - pg-data-MeshAI:/var/lib/postgresql/data

volumes:
  pg-data-MeshAI:
networks:
  meshAINetwork:
    name: meshAINetwork
