// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';
import type { QueryOperationTypes as PgTargetQueryOps } from '@prisma/orm-postgres/target/operation-types';

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'3d0a007fcbda6d84cc6c8e70e617618ae080af0df27834020f8d0219b1f2f4c4'>;
export type ExecutionHash =
  ExecutionHashBase<'edb13a3f21b231261476ebc8ba66e746ac577a720b7cfa0e34f90e28376b61c2'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgTargetQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-date@1': {
        readonly output: 'pg/timestamptz-date@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-date@1': {
        readonly output: 'pg/timestamptz-date@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Account: {
      readonly accountId: CodecTypes['pg/uuid@1']['output'];
      readonly provider: 'GOOGLE' | 'GITHUB';
      readonly providerAccountId: CodecTypes['pg/text@1']['output'];
      readonly userId: CodecTypes['pg/uuid@1']['output'];
    };
    readonly People: {
      readonly birthDate: CodecTypes['pg/date-temporal@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly firstName: CodecTypes['pg/text@1']['output'];
      readonly peopleId: CodecTypes['pg/uuid@1']['output'];
      readonly remainingName: CodecTypes['pg/text@1']['output'];
      readonly sex: 'MALE' | 'FEMALE' | 'NON_BINARY' | 'NONE';
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly userId: CodecTypes['pg/uuid@1']['output'];
    };
    readonly PeopleContact: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly isCurrent: CodecTypes['pg/bool@1']['output'];
      readonly peopleContactId: CodecTypes['pg/text@1']['output'];
      readonly peopleId: CodecTypes['pg/uuid@1']['output'];
      readonly phoneWithDDD: CodecTypes['pg/text@1']['output'];
    };
    readonly Role: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly entity: CodecTypes['pg/text@1']['output'];
      readonly roleId: CodecTypes['pg/uuid@1']['output'];
      readonly roleType: 'ABAC' | 'RBAC';
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly userCan: CodecTypes['pg/text@1']['output'];
      readonly userCannot: CodecTypes['pg/text@1']['output'];
    };
    readonly Token: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly tokenId: CodecTypes['pg/uuid@1']['output'];
      readonly type: 'PASSWORD_RECOVER';
      readonly userId: CodecTypes['pg/uuid@1']['output'];
    };
    readonly User: {
      readonly completeName: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly createdOrigin: CodecTypes['pg/int4@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly passwordHash: CodecTypes['pg/text@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly userId: CodecTypes['pg/uuid@1']['output'];
      readonly username: CodecTypes['pg/text@1']['output'] | null;
    };
    readonly UserRole: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly createdBy: CodecTypes['pg/uuid@1']['output'];
      readonly roleId: CodecTypes['pg/uuid@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly userId: CodecTypes['pg/uuid@1']['output'];
      readonly userRoleId: CodecTypes['pg/uuid@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Account: {
      readonly accountId: CodecTypes['pg/uuid@1']['input'];
      readonly provider: 'GOOGLE' | 'GITHUB';
      readonly providerAccountId: CodecTypes['pg/text@1']['input'];
      readonly userId: CodecTypes['pg/uuid@1']['input'];
    };
    readonly People: {
      readonly birthDate: CodecTypes['pg/date-temporal@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly firstName: CodecTypes['pg/text@1']['input'];
      readonly peopleId: CodecTypes['pg/uuid@1']['input'];
      readonly remainingName: CodecTypes['pg/text@1']['input'];
      readonly sex: 'MALE' | 'FEMALE' | 'NON_BINARY' | 'NONE';
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly userId: CodecTypes['pg/uuid@1']['input'];
    };
    readonly PeopleContact: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly isCurrent: CodecTypes['pg/bool@1']['input'];
      readonly peopleContactId: CodecTypes['pg/text@1']['input'];
      readonly peopleId: CodecTypes['pg/uuid@1']['input'];
      readonly phoneWithDDD: CodecTypes['pg/text@1']['input'];
    };
    readonly Role: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly entity: CodecTypes['pg/text@1']['input'];
      readonly roleId: CodecTypes['pg/uuid@1']['input'];
      readonly roleType: 'ABAC' | 'RBAC';
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly userCan: CodecTypes['pg/text@1']['input'];
      readonly userCannot: CodecTypes['pg/text@1']['input'];
    };
    readonly Token: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly tokenId: CodecTypes['pg/uuid@1']['input'];
      readonly type: 'PASSWORD_RECOVER';
      readonly userId: CodecTypes['pg/uuid@1']['input'];
    };
    readonly User: {
      readonly completeName: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly createdOrigin: CodecTypes['pg/int4@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly passwordHash: CodecTypes['pg/text@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly userId: CodecTypes['pg/uuid@1']['input'];
      readonly username: CodecTypes['pg/text@1']['input'] | null;
    };
    readonly UserRole: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly createdBy: CodecTypes['pg/uuid@1']['input'];
      readonly roleId: CodecTypes['pg/uuid@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly userId: CodecTypes['pg/uuid@1']['input'];
      readonly userRoleId: CodecTypes['pg/uuid@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly accounts: {
      readonly account_id: CodecTypes['pg/uuid@1']['output'];
      readonly provider: 'GOOGLE' | 'GITHUB';
      readonly provider_account_id: CodecTypes['pg/text@1']['output'];
      readonly user_id: CodecTypes['pg/uuid@1']['output'];
    };
    readonly people_contacts: {
      readonly created_at: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly is_current: CodecTypes['pg/bool@1']['output'];
      readonly people_contact_id: CodecTypes['pg/text@1']['output'];
      readonly peopleId: CodecTypes['pg/uuid@1']['output'];
      readonly phone_with_ddd: CodecTypes['pg/text@1']['output'];
    };
    readonly peoples: {
      readonly birthDate: CodecTypes['pg/date-temporal@1']['output'];
      readonly created_at: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly firstName: CodecTypes['pg/text@1']['output'];
      readonly people_id: CodecTypes['pg/uuid@1']['output'];
      readonly remainingName: CodecTypes['pg/text@1']['output'];
      readonly sex: 'MALE' | 'FEMALE' | 'NON_BINARY' | 'NONE';
      readonly updated_at: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly user_id: CodecTypes['pg/uuid@1']['output'];
    };
    readonly roles: {
      readonly created_at: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly entity: CodecTypes['pg/text@1']['output'];
      readonly role_id: CodecTypes['pg/uuid@1']['output'];
      readonly role_type: 'ABAC' | 'RBAC';
      readonly updated_at: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly userCan: CodecTypes['pg/text@1']['output'];
      readonly userCannot: CodecTypes['pg/text@1']['output'];
    };
    readonly tokens: {
      readonly created_at: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly token_id: CodecTypes['pg/uuid@1']['output'];
      readonly type: 'PASSWORD_RECOVER';
      readonly user_id: CodecTypes['pg/uuid@1']['output'];
    };
    readonly user_roles: {
      readonly created_at: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly created_by: CodecTypes['pg/uuid@1']['output'];
      readonly role_id: CodecTypes['pg/uuid@1']['output'];
      readonly updated_at: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly user_id: CodecTypes['pg/uuid@1']['output'];
      readonly user_role_id: CodecTypes['pg/uuid@1']['output'];
    };
    readonly users: {
      readonly complete_name: CodecTypes['pg/text@1']['output'];
      readonly created_at: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly created_origin: CodecTypes['pg/int4@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly password_hash: CodecTypes['pg/text@1']['output'];
      readonly updated_at: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly user_id: CodecTypes['pg/uuid@1']['output'];
      readonly username: CodecTypes['pg/text@1']['output'] | null;
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly accounts: {
      readonly account_id: CodecTypes['pg/uuid@1']['input'];
      readonly provider: 'GOOGLE' | 'GITHUB';
      readonly provider_account_id: CodecTypes['pg/text@1']['input'];
      readonly user_id: CodecTypes['pg/uuid@1']['input'];
    };
    readonly people_contacts: {
      readonly created_at: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly is_current: CodecTypes['pg/bool@1']['input'];
      readonly people_contact_id: CodecTypes['pg/text@1']['input'];
      readonly peopleId: CodecTypes['pg/uuid@1']['input'];
      readonly phone_with_ddd: CodecTypes['pg/text@1']['input'];
    };
    readonly peoples: {
      readonly birthDate: CodecTypes['pg/date-temporal@1']['input'];
      readonly created_at: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly firstName: CodecTypes['pg/text@1']['input'];
      readonly people_id: CodecTypes['pg/uuid@1']['input'];
      readonly remainingName: CodecTypes['pg/text@1']['input'];
      readonly sex: 'MALE' | 'FEMALE' | 'NON_BINARY' | 'NONE';
      readonly updated_at: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly user_id: CodecTypes['pg/uuid@1']['input'];
    };
    readonly roles: {
      readonly created_at: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly entity: CodecTypes['pg/text@1']['input'];
      readonly role_id: CodecTypes['pg/uuid@1']['input'];
      readonly role_type: 'ABAC' | 'RBAC';
      readonly updated_at: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly userCan: CodecTypes['pg/text@1']['input'];
      readonly userCannot: CodecTypes['pg/text@1']['input'];
    };
    readonly tokens: {
      readonly created_at: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly token_id: CodecTypes['pg/uuid@1']['input'];
      readonly type: 'PASSWORD_RECOVER';
      readonly user_id: CodecTypes['pg/uuid@1']['input'];
    };
    readonly user_roles: {
      readonly created_at: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly created_by: CodecTypes['pg/uuid@1']['input'];
      readonly role_id: CodecTypes['pg/uuid@1']['input'];
      readonly updated_at: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly user_id: CodecTypes['pg/uuid@1']['input'];
      readonly user_role_id: CodecTypes['pg/uuid@1']['input'];
    };
    readonly users: {
      readonly complete_name: CodecTypes['pg/text@1']['input'];
      readonly created_at: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly created_origin: CodecTypes['pg/int4@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly password_hash: CodecTypes['pg/text@1']['input'];
      readonly updated_at: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly user_id: CodecTypes['pg/uuid@1']['input'];
      readonly username: CodecTypes['pg/text@1']['input'] | null;
    };
  };
};

export namespace Models {
  export type public_Account = {
    accountId: CodecTypes['pg/uuid@1']['output'];
    provider: 'GOOGLE' | 'GITHUB';
    providerAccountId: CodecTypes['pg/text@1']['output'];
    userId: CodecTypes['pg/uuid@1']['output'];
    user: public_User;
    readonly [RelationKeys]?: 'user';
  };
  export type public_People = {
    birthDate: CodecTypes['pg/date-temporal@1']['output'];
    createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    firstName: CodecTypes['pg/text@1']['output'];
    peopleId: CodecTypes['pg/uuid@1']['output'];
    remainingName: CodecTypes['pg/text@1']['output'];
    sex: 'MALE' | 'FEMALE' | 'NON_BINARY' | 'NONE';
    updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    userId: CodecTypes['pg/uuid@1']['output'];
    peopleContact: public_PeopleContact[];
    user: public_User;
    readonly [RelationKeys]?: 'peopleContact' | 'user';
  };
  export type public_PeopleContact = {
    createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    email: CodecTypes['pg/text@1']['output'];
    isCurrent: CodecTypes['pg/bool@1']['output'];
    peopleContactId: CodecTypes['pg/text@1']['output'];
    peopleId: CodecTypes['pg/uuid@1']['output'];
    phoneWithDDD: CodecTypes['pg/text@1']['output'];
    people: public_People;
    readonly [RelationKeys]?: 'people';
  };
  export type public_Role = {
    createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    entity: CodecTypes['pg/text@1']['output'];
    roleId: CodecTypes['pg/uuid@1']['output'];
    roleType: 'ABAC' | 'RBAC';
    updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    userCan: CodecTypes['pg/text@1']['output'];
    userCannot: CodecTypes['pg/text@1']['output'];
    userRoles: public_UserRole[];
    readonly [RelationKeys]?: 'userRoles';
  };
  export type public_Token = {
    createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    tokenId: CodecTypes['pg/uuid@1']['output'];
    type: 'PASSWORD_RECOVER';
    userId: CodecTypes['pg/uuid@1']['output'];
    user: public_User;
    readonly [RelationKeys]?: 'user';
  };
  export type public_User = {
    completeName: CodecTypes['pg/text@1']['output'];
    createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    createdOrigin: CodecTypes['pg/int4@1']['output'];
    email: CodecTypes['pg/text@1']['output'];
    passwordHash: CodecTypes['pg/text@1']['output'];
    updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    userId: CodecTypes['pg/uuid@1']['output'];
    username: CodecTypes['pg/text@1']['output'] | null;
    owns_account: public_Account[];
    people_id: public_People | null;
    roles: public_UserRole[];
    tokens: public_Token[];
    readonly [RelationKeys]?: 'owns_account' | 'people_id' | 'roles' | 'tokens';
  };
  export type public_UserRole = {
    createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    createdBy: CodecTypes['pg/uuid@1']['output'];
    roleId: CodecTypes['pg/uuid@1']['output'];
    updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    userId: CodecTypes['pg/uuid@1']['output'];
    userRoleId: CodecTypes['pg/uuid@1']['output'];
    roles: public_Role;
    user: public_User;
    readonly [RelationKeys]?: 'roles' | 'user';
  };
}

export declare const models: {
  public: {
    Account: Models.public_Account;
    People: Models.public_People;
    PeopleContact: Models.public_PeopleContact;
    Role: Models.public_Role;
    Token: Models.public_Token;
    User: Models.public_User;
    UserRole: Models.public_UserRole;
  };
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly accounts: {
              columns: {
                readonly account_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly provider: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly provider_account_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly user_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
              };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'accounts_user_id_idx_6c952402';
                  readonly prefix: 'accounts_user_id_idx';
                  readonly columns: readonly ['user_id'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'accounts';
                    readonly columns: readonly ['user_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'users';
                    readonly columns: readonly ['user_id'];
                  };
                },
              ];
            };
            readonly people_contacts: {
              columns: {
                readonly created_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly email: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly is_current: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                };
                readonly peopleId: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly people_contact_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly phone_with_ddd: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['people_contact_id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'people_contacts_peopleId_idx_5c7b58a2';
                  readonly prefix: 'people_contacts_peopleId_idx';
                  readonly columns: readonly ['peopleId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'people_contacts';
                    readonly columns: readonly ['peopleId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'peoples';
                    readonly columns: readonly ['people_id'];
                  };
                },
              ];
            };
            readonly peoples: {
              columns: {
                readonly birthDate: {
                  readonly nativeType: 'date';
                  readonly codecId: 'pg/date-temporal@1';
                  readonly nullable: false;
                };
                readonly created_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly firstName: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly people_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly remainingName: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly sex: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly updated_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                };
                readonly user_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['people_id'] };
              uniques: readonly [{ readonly columns: readonly ['user_id'] }];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'peoples';
                    readonly columns: readonly ['user_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'users';
                    readonly columns: readonly ['user_id'];
                  };
                },
              ];
            };
            readonly roles: {
              columns: {
                readonly created_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly entity: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly role_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly role_type: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly updated_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                };
                readonly userCan: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly userCannot: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['role_id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly tokens: {
              columns: {
                readonly created_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly token_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly type: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly user_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['token_id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'tokens_user_id_idx_6c952402';
                  readonly prefix: 'tokens_user_id_idx';
                  readonly columns: readonly ['user_id'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'tokens';
                    readonly columns: readonly ['user_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'users';
                    readonly columns: readonly ['user_id'];
                  };
                },
              ];
            };
            readonly user_roles: {
              columns: {
                readonly created_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly created_by: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly role_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly updated_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                };
                readonly user_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly user_role_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['user_role_id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'user_roles_role_id_idx_d9467c50';
                  readonly prefix: 'user_roles_role_id_idx';
                  readonly columns: readonly ['role_id'];
                  readonly unique: false;
                },
                {
                  readonly name: 'user_roles_user_id_idx_6c952402';
                  readonly prefix: 'user_roles_user_id_idx';
                  readonly columns: readonly ['user_id'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'user_roles';
                    readonly columns: readonly ['user_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'users';
                    readonly columns: readonly ['user_id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'user_roles';
                    readonly columns: readonly ['role_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'roles';
                    readonly columns: readonly ['role_id'];
                  };
                },
              ];
            };
            readonly users: {
              columns: {
                readonly complete_name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly created_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly created_origin: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly email: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly password_hash: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly updated_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                };
                readonly user_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly username: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['user_id'] };
              uniques: readonly [{ readonly columns: readonly ['email'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
          readonly valueSet: {
            readonly AccountProvider: {
              readonly kind: 'valueSet';
              readonly values: readonly ['GOOGLE', 'GITHUB'];
            };
            readonly PeopleSex: {
              readonly kind: 'valueSet';
              readonly values: readonly ['MALE', 'FEMALE', 'NON_BINARY', 'NONE'];
            };
            readonly RoleType: {
              readonly kind: 'valueSet';
              readonly values: readonly ['ABAC', 'RBAC'];
            };
            readonly TokenType: {
              readonly kind: 'valueSet';
              readonly values: readonly ['PASSWORD_RECOVER'];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly accounts: { readonly namespace: 'public' & NamespaceId; readonly model: 'Account' };
    readonly people_contacts: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'PeopleContact';
    };
    readonly peoples: { readonly namespace: 'public' & NamespaceId; readonly model: 'People' };
    readonly roles: { readonly namespace: 'public' & NamespaceId; readonly model: 'Role' };
    readonly tokens: { readonly namespace: 'public' & NamespaceId; readonly model: 'Token' };
    readonly user_roles: { readonly namespace: 'public' & NamespaceId; readonly model: 'UserRole' };
    readonly users: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Account: {
            readonly fields: {
              readonly accountId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly provider: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly providerAccountId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
            };
            readonly relations: {
              readonly user: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['userId'];
                  readonly targetFields: readonly ['userId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'accounts';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly accountId: { readonly column: 'account_id' };
                readonly provider: { readonly column: 'provider' };
                readonly providerAccountId: { readonly column: 'provider_account_id' };
                readonly userId: { readonly column: 'user_id' };
              };
            };
          };
          readonly People: {
            readonly fields: {
              readonly birthDate: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/date-temporal@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly firstName: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly peopleId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly remainingName: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly sex: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
            };
            readonly relations: {
              readonly peopleContact: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'PeopleContact';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['peopleId'];
                  readonly targetFields: readonly ['peopleId'];
                };
              };
              readonly user: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['userId'];
                  readonly targetFields: readonly ['userId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'peoples';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly birthDate: { readonly column: 'birthDate' };
                readonly createdAt: { readonly column: 'created_at' };
                readonly firstName: { readonly column: 'firstName' };
                readonly peopleId: { readonly column: 'people_id' };
                readonly remainingName: { readonly column: 'remainingName' };
                readonly sex: { readonly column: 'sex' };
                readonly updatedAt: { readonly column: 'updated_at' };
                readonly userId: { readonly column: 'user_id' };
              };
            };
          };
          readonly PeopleContact: {
            readonly fields: {
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly isCurrent: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly peopleContactId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly peopleId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly phoneWithDDD: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly people: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'People';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['peopleId'];
                  readonly targetFields: readonly ['peopleId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'people_contacts';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly createdAt: { readonly column: 'created_at' };
                readonly email: { readonly column: 'email' };
                readonly isCurrent: { readonly column: 'is_current' };
                readonly peopleContactId: { readonly column: 'people_contact_id' };
                readonly peopleId: { readonly column: 'peopleId' };
                readonly phoneWithDDD: { readonly column: 'phone_with_ddd' };
              };
            };
          };
          readonly Role: {
            readonly fields: {
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly entity: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly roleId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly roleType: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly userCan: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly userCannot: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly userRoles: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'UserRole';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['roleId'];
                  readonly targetFields: readonly ['roleId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'roles';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly createdAt: { readonly column: 'created_at' };
                readonly entity: { readonly column: 'entity' };
                readonly roleId: { readonly column: 'role_id' };
                readonly roleType: { readonly column: 'role_type' };
                readonly updatedAt: { readonly column: 'updated_at' };
                readonly userCan: { readonly column: 'userCan' };
                readonly userCannot: { readonly column: 'userCannot' };
              };
            };
          };
          readonly Token: {
            readonly fields: {
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly tokenId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly type: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
            };
            readonly relations: {
              readonly user: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['userId'];
                  readonly targetFields: readonly ['userId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'tokens';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly createdAt: { readonly column: 'created_at' };
                readonly tokenId: { readonly column: 'token_id' };
                readonly type: { readonly column: 'type' };
                readonly userId: { readonly column: 'user_id' };
              };
            };
          };
          readonly User: {
            readonly fields: {
              readonly completeName: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly createdOrigin: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly passwordHash: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly username: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly owns_account: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Account';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['userId'];
                  readonly targetFields: readonly ['userId'];
                };
              };
              readonly people_id: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'People';
                };
                readonly cardinality: '1:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['userId'];
                  readonly targetFields: readonly ['userId'];
                };
              };
              readonly roles: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'UserRole';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['userId'];
                  readonly targetFields: readonly ['userId'];
                };
              };
              readonly tokens: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Token';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['userId'];
                  readonly targetFields: readonly ['userId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'users';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly completeName: { readonly column: 'complete_name' };
                readonly createdAt: { readonly column: 'created_at' };
                readonly createdOrigin: { readonly column: 'created_origin' };
                readonly email: { readonly column: 'email' };
                readonly passwordHash: { readonly column: 'password_hash' };
                readonly updatedAt: { readonly column: 'updated_at' };
                readonly userId: { readonly column: 'user_id' };
                readonly username: { readonly column: 'username' };
              };
            };
          };
          readonly UserRole: {
            readonly fields: {
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly createdBy: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly roleId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly userRoleId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
            };
            readonly relations: {
              readonly roles: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'Role' };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['roleId'];
                  readonly targetFields: readonly ['roleId'];
                };
              };
              readonly user: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['userId'];
                  readonly targetFields: readonly ['userId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'user_roles';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly createdAt: { readonly column: 'created_at' };
                readonly createdBy: { readonly column: 'created_by' };
                readonly roleId: { readonly column: 'role_id' };
                readonly updatedAt: { readonly column: 'updated_at' };
                readonly userId: { readonly column: 'user_id' };
                readonly userRoleId: { readonly column: 'user_role_id' };
              };
            };
          };
        };
        readonly enum: {
          readonly AccountProvider: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'GOOGLE'; readonly value: 'GOOGLE' },
              { readonly name: 'GITHUB'; readonly value: 'GITHUB' },
            ];
          };
          readonly PeopleSex: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'MALE'; readonly value: 'MALE' },
              { readonly name: 'FEMALE'; readonly value: 'FEMALE' },
              { readonly name: 'NON_BINARY'; readonly value: 'NON_BINARY' },
              { readonly name: 'NONE'; readonly value: 'NONE' },
            ];
          };
          readonly RoleType: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'ABAC'; readonly value: 'ABAC' },
              { readonly name: 'RBAC'; readonly value: 'RBAC' },
            ];
          };
          readonly TokenType: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'PASSWORD_RECOVER'; readonly value: 'PASSWORD_RECOVER' },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly insertOnConflictSkip: true;
      readonly insertOnConflictWithoutTarget: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'people_contacts';
            readonly field: 'people_contact_id';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'peoples';
            readonly field: 'people_id';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'instantNow'; readonly kind: 'generator' };
          readonly onUpdate: { readonly id: 'instantNow'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'peoples';
            readonly field: 'updated_at';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'roles';
            readonly field: 'role_id';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'instantNow'; readonly kind: 'generator' };
          readonly onUpdate: { readonly id: 'instantNow'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'roles';
            readonly field: 'updated_at';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'tokens';
            readonly field: 'token_id';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'instantNow'; readonly kind: 'generator' };
          readonly onUpdate: { readonly id: 'instantNow'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'user_roles';
            readonly field: 'updated_at';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'user_roles';
            readonly field: 'user_role_id';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'instantNow'; readonly kind: 'generator' };
          readonly onUpdate: { readonly id: 'instantNow'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'users';
            readonly field: 'updated_at';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'users';
            readonly field: 'user_id';
            readonly namespace: 'public';
          };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
